app:
  jwt:
    secret: thismyverysecurekeyforjwtauthenticationtoken123456
    expiration-ms: 1800000 
management:
  tracing:
    sampling:
      probability: 1.0     # trace all requests (like sleuth.sampler.probability)

  endpoints:
    web:
      exposure:
        include: "*"       # expose actuator endpoints (optional, but useful)

# OpenTelemetry OTLP exporter (Collector running at localhost:4317)
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317

logging:
  pattern:
    level: "%5p [${spring.application.name}, traceId=%X{traceId:-}, spanId=%X{spanId:-}]"

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 234433312724-24vaq5k7tu3dtc8l5cdugirpet5jtbgc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          github:
            client-id: Ov23liEEqYCsYFMcBwlP
            client-secret: 44df3bde57a4fe849c6f9dfafb9934cdae9a5340
            scope:
              - user:email

        provider:
          github:
            user-info-uri: https://api.github.com/user
  mail:
    host: smtp.gmail.com
    port: 587
    username: vyomkorat2020@gmail.com   
    password: yykb fqyi xbeh ujmv   
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
